---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/dynatrace-operator.dynatrace: ''
  name: dynatrace-operator
  namespace: dynatrace
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: dynatrace-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: dynatrace-operator.v0.2.2
