---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-appset
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/raffaelespazzoli/gitops-multicluster.git
        directories:
          - path: kustomize/cluster-overlays/${cluster}/*
    - git:
        repoURL: https://github.com/raffaelespazzoli/gitops-multicluster.git
        directories:
          - path: helm/cluster-overlays/${cluster}/*
        template:
          spec:
            source:
              path: helm/charts/{{.path.basename}}
              helm:
                valueFiles:
                - ../../cluster-overlays/${cluster}/{{.path.basename}}/values.yaml
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: application-type
              operator: In
              values:
                - operator
        - matchExpressions:
            - key: application-type
              operator: In
              values:
                - configuration
        - matchExpressions: []                                 
  template:
    metadata:
      name: '{{ .path.basename }}'
      labels:
        application-type: {{ .path.basename | splitList "-" | last }}
    spec:
      destination:
        server: "https://kubernetes.default.svc"
      project: default
      syncPolicy:
        automated: {}
        retry:
          limit: 10
          backoff:
            duration: "120s"
            factor: 5
            maxDuration: "10m0s"
      source:
        path: "{{.path.path}}"
        repoURL: "https://github.com/raffaelespazzoli/gitops-multicluster.git"

