---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../bases/dynatrace-operator

patchesStrategicMerge:
- |-
  apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: dynatrace-operator
    namespace: dynatrace
  spec:
    startingCSV: dynatrace-operator.v0.2.2